openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://api.example.local'
paths:
  /v1/auth/login:
    post:
      summary: "Login user\n\nLogin using email and password"
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: ''
                  example: quia
                password:
                  type: string
                  description: ''
                  example: excepturi
              required:
                - email
                - password
      security: []
  /v1/auth/logout:
    post:
      summary: "Logout\n\nLogout user"
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Authentication
  /v1/contacts:
    get:
      summary: 'Contacts List'
      description: ''
      parameters:
        -
          in: query
          name: page
          description: ''
          example: 18
          required: false
          schema:
            type: integer
            description: ''
            example: 18
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Contacts
  /v1/contact:
    post:
      summary: "Add New Contact\n\nbodyParam user_id string required\nbodyParam first_name string required\nbodyParam last_name string required\nbodyParam email string\nbodyParam cp_no string"
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Contacts
  '/v1/contact/{id}':
    get:
      summary: 'Show Contact'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Contacts
    put:
      summary: "Update Contact Info\n\nqueryUrl id string required\nbodyParam user_id string required\nbodyParam first_name string required\nbodyParam last_name string required\nbodyParam email string\nbodyParam cp_no string"
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Contacts
    delete:
      summary: 'Delete Contact'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Contacts
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the contact.'
        example: est
        required: true
        schema:
          type: string
  /v1/groups:
    get:
      summary: 'Groups List'
      description: ''
      parameters:
        -
          in: query
          name: page
          description: ''
          example: 6
          required: false
          schema:
            type: integer
            description: ''
            example: 6
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Groups
  '/v1/group/{id}':
    delete:
      summary: 'Delete group'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Groups
    put:
      summary: 'Update Group Info'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Groups
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: eveniet
                description:
                  type: string
                  description: ''
                  example: ea
              required:
                - name
    get:
      summary: 'Show Group'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Groups
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the group.'
        example: enim
        required: true
        schema:
          type: string
  /v1/group:
    post:
      summary: 'Add New Group'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Groups
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: accusamus
                description:
                  type: string
                  description: ''
                  example: maxime
              required:
                - name
  /v1/users:
    get:
      summary: 'Users List'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Users
  '/v1/user/{id}':
    put:
      summary: 'Update User Info'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: multipart/form-data
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Users
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  description: ''
                  example: assumenda
                last_name:
                  type: string
                  description: ''
                  example: quam
                email:
                  type: string
                  description: ''
                  example: expedita
                password:
                  type: string
                  description: ''
                  example: ut
                profile_picture:
                  type: string
                  format: binary
                  description: ''
                group_id:
                  type: string
                  description: ''
                  example: nisi
                is_super_admin:
                  type: boolean
                  description: ''
                  example: false
              required:
                - first_name
                - last_name
                - email
                - password
                - group_id
    get:
      summary: 'Show User'
      description: ''
      parameters:
        -
          in: query
          name: id
          description: ''
          example: sed
          required: true
          schema:
            type: string
            description: ''
            example: sed
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Users
    delete:
      summary: 'Delete User'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Users
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the user.'
        example: 39356693-1b71-40f3-a650-9ead72c6139d
        required: true
        schema:
          type: string
  /v1/user:
    post:
      summary: 'Add New User'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: multipart/form-data
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Users
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  description: ''
                  example: corporis
                last_name:
                  type: string
                  description: ''
                  example: accusantium
                email:
                  type: string
                  description: ''
                  example: consequatur
                password:
                  type: string
                  description: ''
                  example: corporis
                profile_picture:
                  type: string
                  format: binary
                  description: ''
                group_id:
                  type: string
                  description: ''
                  example: fugit
                is_super_admin:
                  type: boolean
                  description: ''
                  example: true
                contacts:
                  type: array
                  description: ''
                  example:
                    - []
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                        description: ''
                        example: deleniti
                      first_name:
                        type: string
                        description: ''
                        example: neque
                      last_name:
                        type: string
                        description: ''
                        example: omnis
                      email:
                        type: string
                        description: ''
                        example: enim
                      cp_no:
                        type: string
                        description: ''
                        example: ut
                    required:
                      - first_name
                      - last_name
              required:
                - first_name
                - last_name
                - email
                - password
                - group_id
      security: []
tags:
  -
    name: Authentication
    description: ''
  -
    name: Contacts
    description: ''
  -
    name: Groups
    description: ''
  -
    name: Users
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: ''
security:
  -
    default: []
